import { int, mysqlEnum, mysqlTable, text, timestamp, varchar, boolean, decimal } from "drizzle-orm/mysql-core";

/**
 * Core user table backing auth flow.
 */
export const users = mysqlTable("users", {
  id: int("id").autoincrement().primaryKey(),
  openId: varchar("openId", { length: 64 }).unique(),
  name: text("name"),
  email: varchar("email", { length: 320 }),
  loginMethod: varchar("loginMethod", { length: 64 }),
  passwordHash: text("passwordHash"),
  role: mysqlEnum("role", ["user", "admin"]).default("user").notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
  lastSignedIn: timestamp("lastSignedIn").defaultNow().notNull(),
});

export type User = typeof users.$inferSelect;
export type InsertUser = typeof users.$inferInsert;

/**
 * Blockchain addresses being monitored
 */
export const addresses = mysqlTable("addresses", {
  id: int("id").autoincrement().primaryKey(),
  address: varchar("address", { length: 42 }).notNull().unique(),
  network: mysqlEnum("network", ["ethereum", "bsc", "polygon"]).notNull(),
  riskScore: int("riskScore").notNull().default(0), // 0-100
  isWhitelisted: boolean("isWhitelisted").notNull().default(false),
  isBlacklisted: boolean("isBlacklisted").notNull().default(false),
  label: text("label"),
  totalTransactions: int("totalTransactions").notNull().default(0),
  suspiciousTransactions: int("suspiciousTransactions").notNull().default(0),
  firstSeen: timestamp("firstSeen").defaultNow().notNull(),
  lastSeen: timestamp("lastSeen").defaultNow().notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type Address = typeof addresses.$inferSelect;
export type InsertAddress = typeof addresses.$inferInsert;

/**
 * Blockchain transactions
 */
export const transactions = mysqlTable("transactions", {
  id: int("id").autoincrement().primaryKey(),
  txHash: varchar("txHash", { length: 66 }).notNull().unique(),
  network: mysqlEnum("network", ["ethereum", "bsc", "polygon"]).notNull(),
  fromAddress: varchar("fromAddress", { length: 42 }).notNull(),
  toAddress: varchar("toAddress", { length: 42 }).notNull(),
  value: varchar("value", { length: 78 }).notNull(), // Store as string to avoid precision loss
  gasPrice: varchar("gasPrice", { length: 78 }),
  gasUsed: varchar("gasUsed", { length: 78 }),
  blockNumber: int("blockNumber").notNull(),
  timestamp: timestamp("timestamp").notNull(),
  isSuspicious: boolean("isSuspicious").notNull().default(false),
  riskScore: int("riskScore").notNull().default(0), // 0-100
  riskFactors: text("riskFactors"), // JSON array of detected risk factors
  mlPrediction: varchar("mlPrediction", { length: 20 }), // "safe", "suspicious", "high_risk"
  mlConfidence: int("mlConfidence"), // 0-100
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export type Transaction = typeof transactions.$inferSelect;
export type InsertTransaction = typeof transactions.$inferInsert;

/**
 * Fraud alerts generated by the system
 */
export const alerts = mysqlTable("alerts", {
  id: int("id").autoincrement().primaryKey(),
  transactionId: int("transactionId").notNull(),
  severity: mysqlEnum("severity", ["low", "medium", "high", "critical"]).notNull(),
  title: varchar("title", { length: 255 }).notNull(),
  description: text("description").notNull(),
  riskFactors: text("riskFactors"), // JSON array
  isRead: boolean("isRead").notNull().default(false),
  isResolved: boolean("isResolved").notNull().default(false),
  resolvedBy: int("resolvedBy"),
  resolvedAt: timestamp("resolvedAt"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export type Alert = typeof alerts.$inferSelect;
export type InsertAlert = typeof alerts.$inferInsert;

/**
 * Generated reports
 */
export const reports = mysqlTable("reports", {
  id: int("id").autoincrement().primaryKey(),
  title: varchar("title", { length: 255 }).notNull(),
  type: mysqlEnum("type", ["daily", "weekly", "monthly", "custom"]).notNull(),
  startDate: timestamp("startDate").notNull(),
  endDate: timestamp("endDate").notNull(),
  totalTransactions: int("totalTransactions").notNull(),
  suspiciousTransactions: int("suspiciousTransactions").notNull(),
  alertsGenerated: int("alertsGenerated").notNull(),
  pdfUrl: text("pdfUrl"),
  generatedBy: int("generatedBy").notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export type Report = typeof reports.$inferSelect;
export type InsertReport = typeof reports.$inferInsert;

/**
 * System configuration
 */
export const systemConfig = mysqlTable("systemConfig", {
  id: int("id").autoincrement().primaryKey(),
  key: varchar("key", { length: 100 }).notNull().unique(),
  value: text("value").notNull(),
  description: text("description"),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type SystemConfig = typeof systemConfig.$inferSelect;
export type InsertSystemConfig = typeof systemConfig.$inferInsert;
